IKApplication/Presentation/IKApplication.MVC/Areas/CompanyAdministrator/Controllers/CompanyController.cs
using IKApplication.Application.AbstractServices;
using IKApplication.Application.DTOs.CompanyDTOs;
using IKApplication.Application.DTOs.UserDTOs;
using IKApplication.Infrastructure.ConcreteServices;
using IKApplication.MVC.ResultMessages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using static IKApplication.MVC.ResultMessages.Messages;
using System.Security.Policy;

namespace IKApplication.MVC.Areas.SiteAdministrator.Controllers
{
    [Area("CompanyAdministrator")]
    [Authorize(Roles = "Company Administrator")]
    public class CompanyController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly IToastNotification _toast;
        public CompanyController(ICompanyService companyService, IToastNotification toast)
        {
            _companyService = companyService;
            _toast = toast;
        }
        public async Task<IActionResult> Update(Guid id)
        {
            return View(await _companyService.GetById(id));
        }
        [HttpPost]
        public async Task<IActionResult> Update(CompanyUpdateDTO updateCompanyDTO)
        {
            if (ModelState.IsValid)
            {
                await _companyService.Update(updateCompanyDTO);
                _toast.AddSuccessToastMessage(Messages.Company.Update(updateCompanyDTO.Name), new ToastrOptions { Title = "Updating Company" });
                return RedirectToAction("Update", "Company");
            }

            _toast.AddErrorToastMessage(Messages.Errors.Error(), new ToastrOptions { Title = "Updating Company" });
            return View(updateCompanyDTO);
        }
    }
}

IKApplication/Presentation/IKApplication.MVC/Areas/SiteAdministrator/Controllers/CompanyController.cs
using IKApplication.Application.AbstractServices;
using IKApplication.Application.DTOs.CompanyDTOs;
using IKApplication.Application.VMs.CompanyVMs;
using IKApplication.Application.VMs.ExcelVMs;
using IKApplication.Application.VMs.ExpenseVMs;
using IKApplication.Application.VMs.UserVMs;
using IKApplication.Infrastructure.ConcreteServices;
using IKApplication.MVC.ResultMessages;
using iTextSharp.text.pdf;
using iTextSharp.text;
using iTextSharp.tool.xml;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using OfficeOpenXml;
using System.Text;
using static IKApplication.MVC.ResultMessages.Messages;
using IKApplication.Application.DTOs.ReportDTOs;
using IKApplication.Domain.Enums;

namespace IKApplication.MVC.Areas.CompanyAdministrator.Controllers
{
    [Area("SiteAdministrator")]
    [Authorize(Roles = "Site Administrator")]
    public class CompanyController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly IToastNotification _toast;
        private readonly IReportService _reportService;
        private readonly IAppUserService _appUserService;

        public CompanyController(ICompanyService companyService, IToastNotification toast, IReportService reportService, IAppUserService appUserService)
        {
            _companyService = companyService;
            _toast = toast;
            _reportService = reportService;
            _appUserService = appUserService;
        }

        public async Task<IActionResult> Index()
        {
            var companies = await _companyService.GetAllCompanies();
            return View(companies);
        }

        public async Task<IActionResult> Update(Guid id)
        {
            return View(await _companyService.GetById(id));
        }

        [HttpPost]
        public async Task<IActionResult> Update(CompanyUpdateDTO updateCompanyDTO)
        {
            if (ModelState.IsValid)
            {
                await _companyService.Update(updateCompanyDTO);
                _toast.AddSuccessToastMessage(Company.Update(updateCompanyDTO.Name), new ToastrOptions { Title = "Updating Company" });
                return RedirectToAction("Index", "Dashboard");
            }

            _toast.AddErrorToastMessage(Errors.Error(), new ToastrOptions { Title = "Updating Company" });
            return View(updateCompanyDTO);
        }

        [HttpGet]
        public async Task<IActionResult> CompanyExcel()
        {
            var stream = new MemoryStream();

            var date = DateTime.Now;
            var startDate = new DateTime(date.Year, date.Month, 1);
            var endDate = new DateTime(date.Year, date.Month + 1, 1);

            List<CompanyVM> allCompanies = await _companyService.GetAllCompanies();
            var currentUser = await _appUserService.GetCurrentUserInfo(User.Identity.Name);

            ExcelPackage pck = new ExcelPackage(stream);
            ExcelWorksheet ws = pck.Workbook.Worksheets.Add("Companies");

            ws.Cells["A1"].Value = "All Companies";
            ws.Cells["A1:B2"].Style.Font.Bold = true;

            ws.Cells["A2"].Value = "Date";
            ws.Cells["B2"].Value = $"{date.Day} - {date.Month} - {date.Year}";

            ws.Cells["A5"].Value = "Total Company Count: ";
            ws.Cells["A5"].Style.Border.Left.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
            ws.Cells["A5"].Style.Border.Right.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
            ws.Cells["A5"].Style.Border.Top.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
            ws.Cells["A5"].Style.Border.Bottom.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;

            ws.Cells["B5"].Value = allCompanies.Count;
            ws.Cells["B5"].Style.Border.Left.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
            ws.Cells["B5"].Style.Border.Right.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
            ws.Cells["B5"].Style.Border.Top.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
            ws.Cells["B5"].Style.Border.Bottom.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;

            ws.Cells["A5"].Style.Font.Bold = true;
            ws.Cells["B5"].Style.Font.Bold = true;

            ws.Cells["A6"].Value = "Company Name";
            ws.Cells["B6"].Value = "Email Address";
            ws.Cells["C6"].Value = "Phone Number";
            ws.Cells["D6"].Value = "Sector Name";
            ws.Cells["E6"].Value = "Number of Employees";
            ws.Cells["F6"].Value = "Contact Person";

            ws.Cells["A6:F6"].Style.Border.Left.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
            ws.Cells["A6:F6"].Style.Border.Right.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
            ws.Cells["A6:F6"].Style.Border.Top.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
            ws.Cells["A6:F6"].Style.Border.Bottom.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
            ws.Cells["A6:F6"].Style.Font.Bold = true;

            int rowStart = 7;

            foreach (var company in allCompanies)
            {
                ws.Cells[string.Format("A{0}", rowStart)].Value = company.Name;
                ws.Cells[string.Format("A{0}", rowStart)].Style.Border.Left.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("A{0}", rowStart)].Style.Border.Right.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("A{0}", rowStart)].Style.Border.Top.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("A{0}", rowStart)].Style.Border.Bottom.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;

                ws.Cells[string.Format("B{0}", rowStart)].Value = company.Email;
                ws.Cells[string.Format("B{0}", rowStart)].Style.Border.Left.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("B{0}", rowStart)].Style.Border.Right.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("B{0}", rowStart)].Style.Border.Top.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("B{0}", rowStart)].Style.Border.Bottom.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;

                ws.Cells[string.Format("C{0}", rowStart)].Value = company.PhoneNumber;
                ws.Cells[string.Format("C{0}", rowStart)].Style.Border.Left.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("C{0}", rowStart)].Style.Border.Right.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("C{0}", rowStart)].Style.Border.Top.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("C{0}", rowStart)].Style.Border.Bottom.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;

                ws.Cells[string.Format("D{0}", rowStart)].Value = company.SectorName;
                ws.Cells[string.Format("D{0}", rowStart)].Style.Border.Left.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("D{0}", rowStart)].Style.Border.Right.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("D{0}", rowStart)].Style.Border.Top.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("D{0}", rowStart)].Style.Border.Bottom.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;

                ws.Cells[string.Format("E{0}", rowStart)].Value = company.NumberOfEmployees;
                ws.Cells[string.Format("E{0}", rowStart)].Style.Border.Left.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("E{0}", rowStart)].Style.Border.Right.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("E{0}", rowStart)].Style.Border.Top.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("E{0}", rowStart)].Style.Border.Bottom.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;

                ws.Cells[string.Format("F{0}", rowStart)].Value = company.ContactPerson;
                ws.Cells[string.Format("F{0}", rowStart)].Style.Border.Left.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("F{0}", rowStart)].Style.Border.Right.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("F{0}", rowStart)].Style.Border.Top.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                ws.Cells[string.Format("F{0}", rowStart)].Style.Border.Bottom.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;

                rowStart++;
            }

            ws.Cells["A:AZ"].AutoFitColumns();
            pck.Save();
            stream.Position = 0;

            var report = new CreateReportDTO()
            {
                Id = Guid.NewGuid(),
                Name = $"All_Companies_Report_{date.Month}/{date.Year}",
                ReportPath = "..\\Reports\\" + Guid.NewGuid() + ".xlsx",
                CreatorId = currentUser.Id,
                FileType = FileType.xls,
            };

            using (FileStream file = new FileStream(report.ReportPath, FileMode.Create, System.IO.FileAccess.Write))
            {
                byte[] bytes = new byte[stream.Length];
                stream.Read(bytes, 0, (int)stream.Length);
                file.Write(bytes, 0, bytes.Length);
                stream.Close();
            }

            await _reportService.Create(report);

            return new FileStreamResult(new FileStream(report.ReportPath, FileMode.Open, FileAccess.Read), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        }

        [HttpGet]
        public async Task<FileResult> CompanyPDF()
        {
            List<CompanyVM> allCompanies = await _companyService.GetAllCompanies();

IKApplication/Presentation/IKApplication.MVC/ViewComponents/CompanyListViewComponent.cs
using IKApplication.Application.VMs.CompanyVMs;
using Microsoft.AspNetCore.Mvc;

namespace IKApplication.MVC.ViewComponents
{
    public class CompanyListViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(List<CompanyVM> companies)
        {
            return View(companies);
        }
    }
}

IKApplication/Presentation/IKApplication.MVC/ViewComponents/CompanyUpdateViewComponent.cs
using IKApplication.Application.AbstractServices;
using IKApplication.Application.DTOs.CompanyDTOs;
using Microsoft.AspNetCore.Mvc;

namespace IKApplication.MVC.ViewComponents
{
    public class CompanyUpdateViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(CompanyUpdateDTO company)
        {
            return View(company);
        }
    }
}

IKApplication/Presentation/IKApplication.MVC/Areas/SiteAdministrator/Views/Company/Create.cshtml
@model CompanyCreateDTO

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4">
        <span class="text-muted fw-light">Manage Companies /</span> Create Company
    </h4>
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-4">
                <h5 class="card-header">Create Company</h5>
                <form asp-controller="Company" asp-action="Create" method="post">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="card-body">

                        <div class="form-group">
                            <label asp-for="Name" class="form-label">Name</label><br />
                            <span asp-validation-for="Name" class="text-danger"></span>
                            <input asp-for="Name" type="text" class="form-control mb-3" id="defaultFormControlInput" placeholder="Enter Company Name" aria-describedby="defaultFormControlHelp">
                        </div>

                        <div class="form-group">
                            <label asp-for="Email" class="form-label">Email</label><br />
                            <span asp-validation-for="Email" class="text-danger"></span>
                            <input asp-for="Email" type="email" class="form-control mb-3" id="defaultFormControlInput" placeholder="Enter Company Email" aria-describedby="defaultFormControlHelp">
                        </div>

                        <div class="form-group">
                            <label asp-for="PhoneNumber" class="form-label">Phone Number</label><br />
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                            <input asp-for="PhoneNumber" type="tel" class="form-control mb-3" id="defaultFormControlInput" placeholder="Enter Company Phone Number" aria-describedby="defaultFormControlHelp">
                        </div>

                        <div class="form-group">
                            <label asp-for="Sector" class="form-label">Sector</label><br />
                            <span asp-validation-for="Sector" class="text-danger"></span>
                            <input asp-for="Sector" type="text" class="form-control mb-3" id="defaultFormControlInput" placeholder="Enter Company Sector" aria-describedby="defaultFormControlHelp">
                        </div>

                        <div class="form-group">
                            <label asp-for="NumberOfEmployees" class="form-label">Number Of Employees</label><br />
                            <span asp-validation-for="NumberOfEmployees" class="text-danger"></span>
                            <input asp-for="NumberOfEmployees" type="number" class="form-control mb-3" id="defaultFormControlInput" placeholder="Enter Number of Employees" aria-describedby="defaultFormControlHelp">
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Create Company</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

IKApplication/Presentation/IKApplication.MVC/Areas/SiteAdministrator/Views/Company/Index.cshtml
@await Component.InvokeAsync("CompanyList", Model)

IKApplication/Presentation/IKApplication.MVC/Areas/SiteAdministrator/Views/Company/Update.cshtml
@await Component.InvokeAsync("CompanyUpdate", Model)