IKApplication/Presentation/IKApplication.MVC/ViewComponents/NavBarViewComponent.cs
using IKApplication.Application.AbstractServices;
using Microsoft.AspNetCore.Mvc;

namespace IKApplication.MVC.ViewComponents
{
    public class NavBarViewComponent : ViewComponent
    {
        private readonly IAppUserService _userService;

        public NavBarViewComponent(IAppUserService userService)
        {
            _userService = userService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {

            return View(await _userService.GetCurrentUserInfo(User.Identity.Name));
        }
    }
}

IKApplication/Presentation/IKApplication.MVC/ViewComponents/SideMenuViewComponent.cs
using IKApplication.Application.AbstractServices;
using IKApplication.Infrastructure.ConcreteServices;
using Microsoft.AspNetCore.Mvc;

namespace IKApplication.MVC.ViewComponents
{
    public class SideMenuViewComponent : ViewComponent
    {
        private readonly IAppUserService _userService;

        public SideMenuViewComponent(IAppUserService userService)
        {
            _userService = userService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            
            return View(await _userService.GetCurrentUserInfo(User.Identity.Name));
        }
    }
}

IKApplication/Presentation/IKApplication.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>IK App</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End Plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/assets/images/favicon.png" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
</head>
<body>
    <!-- container-scroller -->
    <div class="container-scroller">
        <!-- component: SideMenu -->
        @await Component.InvokeAsync("SideMenu")
        <!-- component -->
        <!-- page-body-wrapper -->
        <div class="container-fluid page-body-wrapper">
            <!-- component: NavBar -->
            @await Component.InvokeAsync("NavBar")
            <!-- component -->
            <!-- main-panel -->
            <div class="main-panel">
                <!-- content-wrapper -->
                <div class="content-wrapper">
                    @RenderBody()
                </div>
                <!-- content-wrapper ends -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller ends -->
    <!-- plugins:js -->
    <script src="~/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- inject:js -->
    <script src="~/assets/js/off-canvas.js"></script>
    <script src="~/assets/js/hoverable-collapse.js"></script>
    <script src="~/assets/js/misc.js"></script>
    <script src="~/assets/js/settings.js"></script>
    <script src="~/assets/js/todolist.js"></script>
    <!-- endinject -->
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify")
</body>
</html>

IKApplication/Presentation/IKApplication.MVC/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>IK App</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/assets/images/favicon.png" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <style>
        input:-webkit-autofill, input:-webkit-autofill:focus {
            box-shadow: 0 0 0 1000px #CB647B inset;
            -webkit-text-fill-color: #ffffff;
        }
    </style>
</head>
<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="row w-100 m-0">
                <div class="content-wrapper full-page-wrapper d-flex align-items-center auth login-bg">
                    @RenderBody()
                </div>
                <!-- content-wrapper ends -->
            </div>
            <!-- row ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/assets/js/off-canvas.js"></script>
    <script src="~/assets/js/hoverable-collapse.js"></script>
    <script src="~/assets/js/misc.js"></script>
    <script src="~/assets/js/settings.js"></script>
    <script src="~/assets/js/todolist.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    await Component.InvokeAsync("NToastNotify")
    <!-- endinject -->
</body>
</html>